name: Auto Assign
on:
  issues:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: cfanertipp
          assignees: cfanertipp
          skipKeywords: wip, draft
          numberOfAssignees: 1
